services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Django server
      - "8888:8888"  # Jupyter Notebook
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1  # Ensure logs are output in real-time
    tty: true  # Enable interactive terminal for debugging
    stdin_open: true  # Keep STDIN open for interactive use